### ISSUE TITLE
ErrorExceptionDivision by zero

### ISSUE THREAD

**Issue by bobob89** [unknownworlds/translate#1]
Hi, 
I have a some error, can you help with that?

error there (it is temp domain): 

http://translate.lizasbraids.ru/admin-tool/language-status

tnx

(2/2) ErrorExceptionDivision by zero (View: /var/www/u0667431/translate.lizasbraids.ru/resources/views/adminTool/languageStatus.blade.php)
--
in 65ac57f296c04f27cb79be3cfa56c9a8bb151a92.php line 33
at CompilerEngine->handleViewException(object(ErrorException), 0)in PhpEngine.php line 44
at PhpEngine->evaluatePath('/var/www/u0667431/translate.lizasbraids.ru/storage/framework/views/65ac57f296c04f27cb79be3cfa56c9a8bb151a92.php',array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'languages' => object(Collection), 'languageAdmins' =>array('English' => null, 'Russian' => null), 'unacceptedStrings' => object(Collection), 'acceptedStrings' => object(Collection), 'baseStrings' => 0))in CompilerEngine.php line 59
at CompilerEngine->get('/var/www/u0667431/translate.lizasbraids.ru/resources/views/adminTool/languageStatus.blade.php', array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'languages' => object(Collection), 'languageAdmins' => array('English' => null, 'Russian' => null), 'unacceptedStrings' => object(Collection), 'acceptedStrings' => object(Collection), 'baseStrings' => 0))in View.php line 137
at View->getContents()in View.php line 120
at View->renderContents()in View.php line 85
at View->render()in Response.php line 38
at Response->setContent(object(View))in Response.php line 206
at Response->__construct(object(View))in Router.php line 615
at Router->prepareResponse(object(Request), object(View))in Router.php line 572
at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 30
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckRole.php line 28
at CheckRole->handle(object(Request), object(Closure), 'Root')in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in SubstituteBindings.php line 41
at SubstituteBindings->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Authenticate.php line 43
at Authenticate->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyCsrfToken.php line 65
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php line 64
at StartSession->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in AddQueuedCookiesToResponse.php line 37
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in EncryptCookies.php line 59
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Router.php line 574
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php line 533
at Router->dispatchToRoute(object(Request))in Router.php line 511
at Router->dispatch(object(Request))in Kernel.php line 176
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php line 30
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php line 46
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Kernel.php line 151
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php line 116
at Kernel->handle(object(Request))in index.php line 52

**Comment by acedude** [comment]
Fixed in ab1387ec86c2d6fd16c7933a04d0913704eb2a14
